name: Release
on:
  release:
    types: [published]
jobs:
  package-vscode:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-extension

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: vscode-extension/package-lock.json
      - run: npm i
      - run: npm run compile
      - run: npx vsce package
      - name: Upload VSIX to Release
        uses: softprops/action-gh-release@v2
        with:
          files: vscode-extension/*.vsix

  package-opencode:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-extension

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run build

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            opencode-plugin/dist/tracybot-oc.js
